title: KeyframeCSS
description: Lightweight CSS animation CDN
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

search_enabled: true

aux_links:
  GitHub Repo:
    - "https://github.com/intensed-dev/KeyframeCSS"

nav_external_links:
  - title: CDN
    url: https://cdn.keyframecss.com
